// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace WebResume.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251112030519_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entites.Models.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("middle_name");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("resume");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b8b80fb-1c94-4e46-a069-ee51901b3d3e"),
                            CreatedAt = new DateTime(2025, 11, 12, 9, 43, 42, 361, DateTimeKind.Utc),
                            FirstName = "Sergey",
                            JobTitle = "Specialist",
                            LastName = "Miller",
                            MiddleName = "Ivanovich",
                            TemplateId = new Guid("db58c76e-bcb5-4c6a-ad60-0e61bf3ac11c"),
                            UpdatedAt = new DateTime(2025, 11, 12, 23, 43, 42, 361, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ce078d47-3f43-423f-8c16-a039f805ee88"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 1, 42, 361, DateTimeKind.Utc),
                            FirstName = "John",
                            JobTitle = "Programmer",
                            LastName = "Doe",
                            MiddleName = "middle",
                            TemplateId = new Guid("132805d2-3fc3-457c-86de-40116433c062"),
                            UpdatedAt = new DateTime(2025, 11, 12, 10, 1, 42, 361, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Entites.Models.SpecialInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("special_info_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("special_info");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4b94a1a-ac14-420e-9c67-37ef9b46445f"),
                            Description = "The client is acting suspiciously towards the service, additional attention should be paid to their actions within the service.",
                            Title = "Suspicious activity"
                        },
                        new
                        {
                            Id = new Guid("208c6dbc-77d1-4580-a5e8-3e972e2e1cb7"),
                            Description = "Takes advantage of the service's loyalty and exploits it to commit fraudulent or illegal actions, resulting in financial losses for the service. It is not recommended to provide any services to the client.",
                            Title = "Scammer"
                        });
                });

            modelBuilder.Entity("Entites.Models.Template", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("TemplateKind")
                        .HasColumnType("integer")
                        .HasColumnName("template_kind");

                    b.HasKey("TemplateId");

                    b.ToTable("template");

                    b.HasData(
                        new
                        {
                            TemplateId = new Guid("db58c76e-bcb5-4c6a-ad60-0e61bf3ac11c"),
                            Name = "Default template",
                            TemplateKind = 0
                        },
                        new
                        {
                            TemplateId = new Guid("132805d2-3fc3-457c-86de-40116433c062"),
                            Name = "Premium template",
                            TemplateKind = 1
                        });
                });

            modelBuilder.Entity("Entites.Models.Resume", b =>
                {
                    b.HasOne("Entites.Models.Template", "Template")
                        .WithMany("Resumes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Entites.Models.Template", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
